[project]
name = "newscast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "audioop-lts>=0.2.1",
    "feedparser>=6.0.11",
    "gtts>=2.5.4",
    "langdetect>=1.0.9",
    "pydub>=0.25.1",
]
