name: Deploy

# on:
#   schedule:
#     - cron: '0 * * * *'
#   push:
#     branches:
#       - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'
  
    - name: Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Pull latest changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git pull --rebase

    - name: Run Python script
      run: python generate.py

    - name: Get current date and time
      id: datetime
      run: |
        echo "commit_message='$(date '+%Y/%m/%d %H:%M:%S') UTC'" >> $GITHUB_ENV
        echo "let update_time = new Date('$(date '+%Y/%m/%d %H:%M')');" > public/time.js
        echo "update_time.setHours(update_time.getHours() + 9);" >> public/time.js
        echo "document.getElementById('last_update').innerText = update_time.toLocaleString().slice(0,-3);" >> public/time.js

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "${{ env.commit_message }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        publish_dir: ./public
